apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-files-pvc
spec:
  storageClassName: standard  # Domyślna klasa Storage w GKE
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi