apiVersion: v1
kind: Service
metadata:
  name: nginx  # Nazwa usługi Nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80  # Port, na którym Nginx nasłuchuje
      targetPort: 80  # Port w kontenerze, do którego będzie przekierowany ruch
  selector:
    app: nginx  # Etykieta selektora do wyboru podów Nginx