apiVersion: apps/v1  # Wersja API Kubernetes, która obsługuje zasoby Deployment
kind: Deployment  # Typ zasobu Kubernetes. Deployment zarządza replikami podów.
metadata:
  name: postgres  # Nazwa Deploymentu dla bazy danych PostgreSQL
spec:
  replicas: 1  # Liczba replik podów PostgreSQL. Tutaj ustawiona na 1, co oznacza jedną instancję bazy danych.
  selector:
    matchLabels:
      app: postgres  # Kubernetes używa tego, aby znaleźć pody, które mają etykietę "app: postgres"
  template:
    metadata:
      labels:
        app: postgres  # Etykieta przypisana do podów utworzonych przez ten Deployment. Pody te będą odpowiadać za bazę danych PostgreSQL.
    spec:
      containers:
      - name: postgres  # Nazwa kontenera (jest to nazwa wewnątrz Kubernetes, a nie nazwa obrazu)
        image: postgres:13  # Obraz Dockera, który zostanie użyty. PostgreSQL w wersji 13.
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432  # Port, na którym PostgreSQL będzie nasłuchiwać. Domyślny port PostgreSQL to 5432.
        volumeMounts:
        - name: postgres-data  # Wolumen, który zostanie zamontowany do kontenera, aby przechowywać dane bazy danych.
          mountPath: /var/lib/postgresql/data  # Ścieżka w kontenerze, gdzie PostgreSQL przechowuje dane bazy danych.
      volumes:
      - name: postgres-data  # Definiowanie wolumenu o nazwie "postgres-data", który będzie używany do przechowywania danych.
        persistentVolumeClaim:
          claimName: postgres-pvc