apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP  # Redis powinien być dostępny wewnątrz klastra
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
