apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  POSTGRES_USER: dXNlcm5hbWU=  # Zcoded Base64
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # Zakodowane Base64
  POSTGRES_DB: eW91cl9kYl9uYW1l  # Zakodowane Base64 dla nazwy bazy danych
  DJANGO_SECRET_KEY: ZGlzLWlzLXNlY3JldC1rZXk=  # Zakodowane Base64